name: Run JMeter Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Optionally, you can trigger it on a schedule (e.g., once a day)
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  run-jmeter:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up JDK (Java is required for JMeter)
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # JMeter requires at least Java 8, so Java 11 is fine

    - name: Install JMeter
      run: |
        wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xvzf apache-jmeter-5.4.1.tgz
        mv apache-jmeter-5.4.1 /opt/jmeter
        echo "/opt/jmeter/bin" >> $GITHUB_PATH  # Add JMeter to PATH for future steps

    - name: Run JMeter Test Plan
      run: |
        jmeter -n -t src/test/jmeter/test-plan-new.jmx -l results/output.jtl

    - name: Generate JMeter Report
      run: |
        jmeter -g results/output.jtl -o results/report

    - name: Upload JMeter Report as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-report
        path: results/report
